name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Node.js 설정: 프론트엔드/백엔드 모두 Node 기반이므로 Node 설치
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 백엔드 테스트
      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci

      - name: Test backend
        working-directory: ./server
        run: npm test

      # 프론트엔드 테스트 (React Native)
      # 여기서는 EducationApp 폴더에 있는 package.json 기준
      - name: Install frontend dependencies
        working-directory: ./EducationApp
        run: npm install

      - name: Test frontend
        working-directory: ./EducationApp
        run: npm test -- --ci
